### ISSUE TITLE
Step 1: Project Setup and Core Configuration

### ISSUE THREAD

**Issue by mikeyobrien** [mikeyobrien/90s-static-site-generator#1]
## Acceptance Criteria

Create the foundational project structure for the 90s static site generator with the following components:

### Directory Structure
- Set up a Node.js project with proper package.json configuration
- Create the following directory structure:
  ```
  /
  ├── src/
  │   ├── core/
  │   ├── templates/
  │   ├── utils/
  │   └── index.js
  ├── content/
  │   ├── posts/
  │   ├── pages/
  │   └── assets/
  ├── output/
  ├── themes/
  │   └── default/
  │       ├── layouts/
  │       ├── css/
  │       └── assets/
  └── config.yaml
  ```

### Core Configuration
- Implement a configuration loader that reads from `config.yaml`
- Support the following configuration options:
  ```yaml
  site:
    title: "My 90s Website"
    description: "Welcome to the information superhighway\!"
    url: "http://localhost:8080"
    author: "Webmaster"
  
  build:
    contentDir: "./content"
    outputDir: "./output"
    theme: "default"
  
  features:
    guestbook: true
    hitCounter: true
    webring: true
    midi: false
  ```

### Basic CLI
- Create a simple CLI interface with the following commands:
  - `npm run build` - Build the static site
  - `npm run serve` - Serve the site locally
  - `npm run clean` - Clean the output directory

### Dependencies
- Set up essential dependencies:
  - `yaml` for configuration parsing
  - `marked` for Markdown processing
  - `ejs` for templating
  - `express` for local server
  - `commander` for CLI

This step establishes the foundation that all other features will build upon.
