### ISSUE TITLE
Step 2: Basic Static Site Generation (Markdown to HTML)

### ISSUE THREAD

**Issue by mikeyobrien** [mikeyobrien/90s-static-site-generator#2]
## Acceptance Criteria

Build the core static site generation engine that converts Markdown content to HTML pages.

### Content Processing
- Create a Markdown processor that:
  - Reads all `.md` files from `content/posts/` and `content/pages/`
  - Parses front matter (YAML) for metadata:
    ```yaml
    ---
    title: "My First Blog Post"
    date: 1997-03-15
    author: "CyberDude"
    tags: ["internet", "technology"]
    ---
    ```
  - Converts Markdown content to HTML
  - Supports basic Markdown features (headings, paragraphs, lists, links, images, code blocks)

### Template System
- Implement an EJS-based templating system:
  - Create base layout template in `themes/default/layouts/base.ejs`
  - Support template variables: `title`, `content`, `site` (from config), `page` (current page data)
  - Create separate templates for posts and pages
  - Include common 90s HTML structure (DOCTYPE HTML 4.01 Transitional)

### File Generation
- Generate HTML files maintaining the source directory structure:
  - `content/posts/hello-world.md` → `output/posts/hello-world.html`
  - `content/pages/about.md` → `output/pages/about.html`
  - Copy static assets from `content/assets/` to `output/assets/`

### Basic Styling
- Create a minimal 90s-style CSS file:
  ```css
  body {
    background-color: #C0C0C0;
    font-family: "Times New Roman", serif;
    margin: 20px;
  }
  h1 {
    color: #000080;
    font-size: 24px;
  }
  a {
    color: #0000FF;
    text-decoration: underline;
  }
  a:visited {
    color: #800080;
  }
  ```

### Dependencies
- Depends on: Step 1 (Project Setup)

This step creates the fundamental static site generation functionality that transforms Markdown into styled HTML pages.
