### ISSUE TITLE
Step 6: WebRing Integration and Link Pages

### ISSUE THREAD

**Issue by mikeyobrien** [mikeyobrien/90s-static-site-generator#6]
## Acceptance Criteria

Implement WebRing functionality and create classic 90s-style link pages to connect with the broader retro web community.

### WebRing Support
- Create WebRing integration system:
  - Support for multiple WebRing memberships
  - Generate WebRing navigation widget:
    ```html
    <\!-- WebRing Navigation -->
    <table border="2" bgcolor="#000000" cellpadding="5">
      <tr>
        <td align="center">
          <font color="#FFFF00">Awesome 90s Sites WebRing</font><br>
          [<a href="#">Previous</a>]
          [<a href="#">Random</a>]
          [<a href="#">Next</a>]
          [<a href="#">List Sites</a>]
        </td>
      </tr>
    </table>
    ```
  - Configuration support:
    ```yaml
    webring:
      - name: "Retro Computing Ring"
        id: "retrocomp"
        previousUrl: "https://example.com/prev"
        nextUrl: "https://example.com/next"
        hubUrl: "https://example.com/hub"
      - name: "90s Nostalgia Ring"
        id: "90snostalgia"
        code: "<custom HTML code>"
    ```

### Link Directory Page
- Create automatic link directory generation:
  - Categorized links (Cool Sites, Search Engines, Downloads, etc.)
  - Each link with:
    - Site name
    - Description
    - "Last visited" date
    - Link rating (1-5 stars as GIFs)
    - "Report broken link" mailto
  - Support link data in YAML:
    ```yaml
    links:
      - category: "Cool Sites"
        sites:
          - name: "Joe's Homepage"
            url: "http://geocities.com/joe"
            description: "The coolest site on the net\!"
            rating: 5
    ```

### Banner Exchange
- Implement banner exchange support:
  - 468x60 pixel banner slots
  - Random banner rotation
  - Click tracking (simulated for static sites)
  - Generate "Get my banner" page with HTML code

### Link Validation
- Build-time link checking:
  - Verify all external links
  - Generate report of broken links
  - Option to mark dead links with ❌

### Affiliate/Award Badges
- Support for displaying:
  - "Site of the Day" awards
  - "Best of the Web" badges
  - Affiliate program banners
  - Browser recommendation badges

### Dependencies
- Depends on: Step 5 (Hit Counter and Guestbook)

This step connects the generated site to the wider 90s web community through WebRings and comprehensive link pages.

**Comment by mikeyobrien** [comment]
Plan for Issue #6 — WebRing, link directory, banner exchange, link checker, badges. Assumes #5 delivered YAML data loading + nav hooks; if not, Task 1 includes a minimal loader.

CONFIG SCHEMA (config.yaml additions)
```yaml
webring:                      # list, empty = feature off
  - name: "Ring of Retro"
    id: "retro"
    previousUrl: "https://ring.example/prev.cgi?retro"
    nextUrl: "https://ring.example/next.cgi?retro"
    hubUrl: "https://ring.example/hub.html"
    randomUrl: ""             # optional, defaults to hubUrl
    code: ""                  # optional raw ring HTML; if set, used verbatim instead of themed nav

links:
  dataFile: "data/links.yaml" # categories -> links
  reportBrokenEmail: "webmaster@example.com"
  checkOnBuild: false         # opt-in; slow
  timeoutMs: 5000
  concurrency: 5
  followRedirects: 3
  strict: false               # true = broken links fail the build

banners:
  dataFile: "data/banners.yaml"
  slots: 2                    # 468x60 banners per page
  clickTrackerPage: "click.html"
  exchangePage: true          # emit /banner-exchange/ "get my banner" page

badges:                       # affiliate/award strip, list, empty = off
  - { name: "Netscape Now", image: "assets/badges/netscape.gif", url: "https://example.com", alt: "Netscape Now!" }
```

DATA FILES
- data/links.yaml: categories map -> [{name, url, description, lastVisited: "2026-07-14", rating: 0-5}]
- data/banners.yaml: [{name, url, image, alt, weight>=1}] plus optional myBanner: {image,url,alt} for the exchange page

NEW FILES
- src/webring.js: renderWebrings(rings, themeTpl) -> HTML string. Per ring: raw `code` passthrough if set, else themed nav [<< prev | random | next | list] linking prevUrl/randomUrl||hubUrl/nextUrl/hubUrl. Empty list -> "".
- src/links.js: loadLinks(file) (js-yaml — declare explicit dep, it's only transitive today), buildReportBrokenUrl(link, email) -> mailto with URL-encoded subject+body, renderStars(rating) -> 5 star GIF imgs, buildLinksPage() -> {path:"links/index.html", content}.
- src/banners.js: pickBanners(list, slots, seed=dayOfYear) -> deterministic weighted rotation ((seed + i + cumulative-weight) % totalWeight walk); buildClickHref(url); buildClickTrackerPage() (reads ?to=, counts in localStorage, meta-refresh redirect after 2s); buildExchangePage() (rules + your banner + escaped copy-paste snippet).
- src/badges.js: renderBadges(badges) -> footer strip HTML. (3-line module; fold into webring.js if you prefer.)
- src/link-checker.js: checkUrls(urls, {timeoutMs, concurrency, followRedirects}) using core http/https promise wrapper (node>=14 has no global fetch — do NOT use fetch); HEAD, GET fallback on 405/501, max 3 redirects, skip mailto:/#;/relative. Returns [{url, status:"ok"|"broken"|"error", httpCode?, reason?}]. writeReport(results) -> link-report.html + link-report.json in outputDir.
- Each module: pure functions returning {path, content} records; generator owns all FS writes (testable without disk).

GENERATOR (src/generator.js)
- loadConfig: validate new keys (URL format, rating 0-5, weight>=1, slots 1-4); unknown ring fields ignored.
- build(): after existing renders — collect webringHtml/badgesHtml and inject into shared page context so base.ejs footer shows them on post/page/index/archive when non-empty; emit links page, banner pages, click tracker; if links.checkOnBuild, harvest all absolute URLs (links dir, banners, webring prev/next/hub, badges), run checker, write report; strict && any broken -> throw after report written (report always written first).
- Nav (from #4): append /links/ and /banner-exchange/ entries when enabled.

THEMES (both default and minimal-90s)
- templates/links.ejs: category sections, name+desc, star GIF row (themes/<t>/assets/rating/star_on.gif / star_off.gif — commit tiny placeholders), lastVisited date, "report broken" mailto link per entry.
- templates/banner-exchange.ejs: 468x60 slots preview, your banner, textarea with escaped <a><img></a> snippet.
- partials/webring.ejs + partials/badges.ejs: one ring block per membership, 88x31 badge strip.
- base.ejs: footer gains <%- locals.webringHtml || "" %> and <%- locals.badgesHtml || "" %>.
- click.ejs: query-param redirect stub.
- assets/banners/: commit two 468x60 placeholder GIFs; README notes replace.

TESTS (__tests__, jest, tmp dirs, no network)
- webring.test.js: themed nav contains all URLs + ring name; raw code passthrough; empty -> "".
- links.test.js: YAML load/sort by category; stars = rating on + (5-rating) off; mailto encoding of url+subject; missing rating defaults 0.
- banners.test.js: deterministic pick (same seed = same output, snapshot), weights respected over N seeds, slots <= list length, click href URL-encoded, snippet HTML-escaped.
- link-checker.test.js: mock the module's internal request fn — 200 ok, 404 broken, 405->GET, timeout->error, mailto skipped, concurrency never exceeded (count in-flight).
- generator.test.js (integration): build tmp site with fixture config -> links/index.html, banner-exchange/index.html, click.html exist; webring nav present in a post's HTML; badge strip on index; checker off by default; strict mode throws but still writes report.

RISKS
- Raw `code` injection: trusted (author's own config, like layouts) — document, never interpolate user-content links into it.
- Link checker = slow/flaky builds + CI network: default off, mocked tests only, timeout+concurrency caps, non-fatal unless strict.
- node>=14: no global fetch/AbortController niceties — core https wrapper, manual redirect counting; revisit if #7 bumps node.
- Determinism vs variety: banner rotation seeded by build date only — same look all day per slot; acceptable, documented.
- Missing rating/banner GIFs per theme -> broken images: validate theme asset paths at build, warn loudly.

TASK ORDER (each = failing test -> impl -> pass -> commit)
1. Config schema + validation + defaults
2. links.js data loader + mailto/stars helpers
3. webring.js + partials + base.ejs footer hook
4. links.ejs page + nav entry + placeholder GIFs
5. badges.js strip
6. banners.js rotation + click.html + exchange page
7. link-checker.js + report writer
8. Generator wiring + integration test
9. README config reference section

ACTION: POST_PLAN
